StudentCRUDCBVProject/urls.py
from django.contrib import admin
from django.urls import path
from MyApps1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.StudentsListView.as_view(), name='home'),
    path('detail/<pk>', views.StudentsDetailView.as_view(), name='detail'),
    path('create/', views.StudentsCreateView.as_view(),name='create'),
    path('update/<pk>', views.StudentsUpdateView.as_view(),name='update'),
    path('delete/<pk>', views.StudentsDeleteView.as_view(),name='delete'),
]

MyApps1/models.py
from audioop import reverse

from django.db import models

# Create your models here.
from django.db import models
#from django.core.urlresolvers import reverse
from django.urls import reverse;
#Create your models here....
class Students(models.Model):
    rollno=models.IntegerField();
    name=models.CharField(max_length=128)
    dept=models.CharField(max_length=128)
    marks=models.FloatField(max_length=128)
    def __str__(self):
        return str(self.rollno)+"\t"+str(self.name)+"\t"+str(self.dept)+"\t"+str(self.marks)
    def get_absolute_url(self):
        return reverse('detail',kwargs={'pk':self.pk})

MyApps1/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.shortcuts import render
from MyApps1.models import Students
#from django.core.urlresolvers import reverse_Jazy #old-lib
from django.urls import reverse_lazy	#new-lib
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
# Create your views here.
class StudentsListView(ListView):
    model = Students

class StudentsDetailView(DetailView):
    model = Students

class StudentsCreateView(CreateView):
    model = Students
    #fields=('empno', 'ename','job', 'sal')
    fields = '__all__'

class StudentsUpdateView(UpdateView):
    model = Students
    fields = ('name', 'dept', 'marks')

class StudentsDeleteView(DeleteView):
    model = Students
    success_url = reverse_lazy('home')

templates/MyApps1/Students_confirm_delete.html
<!DOCTYPE html>
{% extends 'MyApps1/base.html'%}
{%block body_block%}
    <h1>Do You Want to Delete ("{Students.id}}->{{students.name }}") Record??</h1>
    <hr />
    <form method="post">
        {%csrf_token%} <br />
        <input type="submit" value="DELETE-STUD-RECORD" /> <br /><br />
        <a href="/home">CANCEL to Go-Back</a>
    </form>
{%endblock%}

templates/MyApps1/Students_detail.html
<!DOCTYPE html>
{% extends 'MyApps1/base.html'%}
{%block body_block%}
    <div>
        <h1>Student-Details!!!</h1>
        <hr />
        <ul>
            <li>ROLL-No : {{students.rollno}}</li>
            <li>NAME : {{students.name|title}}</li>
            <li>DEPT : {{students.dept}}</li>
            <li>MARKS : {{students.marks}}</li>
        </ul>
        <a href="/home">Click to Go-Back</a>
    </div>
{%endblock%}

templates/MyApps1/Students_form.html
<!DOCTYPE html>
{% extends 'MyApps1/base.html'%}
{%block body_block%}
    <h1>Add New Students Here</h1><hr>
    <form method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" value="Insert/Update">
    </form>
{%endblock%}

templates/MyApps1/Students_list.html
<!DOCTYPE html>
{% extends 'MyApps1/base.html' %}
{%block body_block  %}
    <h1>student-information-list</h1>
    <table border="2">
        <thead>
        <th>rollno</th>
        <th>name</th>
        <th>dept</th>
        <th>marks</th>
        <th colspan="3">operations</th>
        </thead>
        {% for Students in students_list %}
            <tr>
                <td>{{Students.rollno }}</td>
                <td>{{Students.name|title }}</td>
                <td>{{Students.dept }}</td>
                <td>{{Students.marks}}</td>
                <td><a href="/detail/{{ Students.id}}">Details</a></td>
                <td><a href="/update/{{ Students.id}}">Update</a></td>
                <td><a href="/delete/{{ Students.id}}">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
    <br/><br/><br/>
    <a href="/create">Insert New-STUDENT-Record HERE</a>
{% endblock %}

templates/MyApps1/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>student-base-view</title>
    <link href="{%static 'css/studstyles.css' %}" rel="stylesheet"/>
</head>
<body>
    <div>
        {%block body_block%}
        {% endblock %}
    </div>

</body>
</html>